// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v4.23.2
// source: api/helloworld/v1/mall.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMallCreateGood = "/api.helloworld.v1.Mall/CreateGood"
const OperationMallCreateProfile = "/api.helloworld.v1.Mall/CreateProfile"
const OperationMallDeleteGoodByID = "/api.helloworld.v1.Mall/DeleteGoodByID"
const OperationMallGetGoodByID = "/api.helloworld.v1.Mall/GetGoodByID"
const OperationMallGetGoodsByKind = "/api.helloworld.v1.Mall/GetGoodsByKind"
const OperationMallGetGoodsByName = "/api.helloworld.v1.Mall/GetGoodsByName"
const OperationMallGetGoodsByUserName = "/api.helloworld.v1.Mall/GetGoodsByUserName"
const OperationMallGetOwnGoods = "/api.helloworld.v1.Mall/GetOwnGoods"
const OperationMallGetProfile = "/api.helloworld.v1.Mall/GetProfile"
const OperationMallLogin = "/api.helloworld.v1.Mall/Login"
const OperationMallRegister = "/api.helloworld.v1.Mall/Register"
const OperationMallUpdateGood = "/api.helloworld.v1.Mall/UpdateGood"
const OperationMallUpdateProfile = "/api.helloworld.v1.Mall/UpdateProfile"

type MallHTTPServer interface {
	// CreateGood 商品信息接口--------------------------------------------------------------------------------------------------
	CreateGood(context.Context, *CreateGoodRequest) (*CreateGoodReply, error)
	// CreateProfile用户信息接口---------------------------------------------------------------------------------------------------
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileReply, error)
	DeleteGoodByID(context.Context, *DeleteGoodByIDRequest) (*DeleteGoodReply, error)
	GetGoodByID(context.Context, *GetGoodByIDRequest) (*GetGoodReply, error)
	GetGoodsByKind(context.Context, *GetGoodsByKindRequest) (*GetGoodsReply, error)
	GetGoodsByName(context.Context, *GetGoodsByNameRequest) (*GetGoodsReply, error)
	GetGoodsByUserName(context.Context, *GetGoodsByUserNameRequest) (*GetGoodsReply, error)
	GetOwnGoods(context.Context, *GetOwnGoodsRequest) (*GetGoodsReply, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// Register 登录注册接口--------------------------------------------------------------------------------------------------
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	UpdateGood(context.Context, *UpdateGoodRequest) (*UpdateGoodReply, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileReply, error)
}

func RegisterMallHTTPServer(s *http.Server, srv MallHTTPServer) {
	r := s.Route("/")
	r.POST("/mall/goods", _Mall_CreateGood0_HTTP_Handler(srv))
	r.PUT("/mall/goods", _Mall_UpdateGood0_HTTP_Handler(srv))
	r.GET("/mall/goods/{Kind}/{Page}/{PageSize}", _Mall_GetGoodsByKind0_HTTP_Handler(srv))
	r.GET("/user/goods/{UserName}/{Page}/{PageSize}", _Mall_GetGoodsByUserName0_HTTP_Handler(srv))
	r.GET("/user/goods/{Page}/{PageSize}", _Mall_GetOwnGoods0_HTTP_Handler(srv))
	r.GET("/user/goods/name/{Name}/{Page}/{PageSize}", _Mall_GetGoodsByName0_HTTP_Handler(srv))
	r.GET("/mall/good/ID/{ID}", _Mall_GetGoodByID0_HTTP_Handler(srv))
	r.DELETE("/user/good/ID/{ID}", _Mall_DeleteGoodByID0_HTTP_Handler(srv))
	r.POST("/user/profile", _Mall_CreateProfile0_HTTP_Handler(srv))
	r.PUT("/user/profile", _Mall_UpdateProfile0_HTTP_Handler(srv))
	r.GET("/user/profile", _Mall_GetProfile0_HTTP_Handler(srv))
	r.POST("/register", _Mall_Register0_HTTP_Handler(srv))
	r.POST("/login", _Mall_Login0_HTTP_Handler(srv))
}

func _Mall_CreateGood0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGoodRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallCreateGood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGood(ctx, req.(*CreateGoodRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGoodReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateGood0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGoodRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateGood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGood(ctx, req.(*UpdateGoodRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateGoodReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetGoodsByKind0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGoodsByKindRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetGoodsByKind)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGoodsByKind(ctx, req.(*GetGoodsByKindRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGoodsReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetGoodsByUserName0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGoodsByUserNameRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetGoodsByUserName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGoodsByUserName(ctx, req.(*GetGoodsByUserNameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGoodsReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetOwnGoods0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOwnGoodsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetOwnGoods)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOwnGoods(ctx, req.(*GetOwnGoodsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGoodsReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetGoodsByName0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGoodsByNameRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetGoodsByName)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGoodsByName(ctx, req.(*GetGoodsByNameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGoodsReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetGoodByID0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGoodByIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetGoodByID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGoodByID(ctx, req.(*GetGoodByIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGoodReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_DeleteGoodByID0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGoodByIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallDeleteGoodByID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGoodByID(ctx, req.(*DeleteGoodByIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteGoodReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_CreateProfile0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallCreateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProfile(ctx, req.(*CreateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_UpdateProfile0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_GetProfile0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_Register0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterReply)
		return ctx.Result(200, reply)
	}
}

func _Mall_Login0_HTTP_Handler(srv MallHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

type MallHTTPClient interface {
	CreateGood(ctx context.Context, req *CreateGoodRequest, opts ...http.CallOption) (rsp *CreateGoodReply, err error)
	CreateProfile(ctx context.Context, req *CreateProfileRequest, opts ...http.CallOption) (rsp *CreateProfileReply, err error)
	DeleteGoodByID(ctx context.Context, req *DeleteGoodByIDRequest, opts ...http.CallOption) (rsp *DeleteGoodReply, err error)
	GetGoodByID(ctx context.Context, req *GetGoodByIDRequest, opts ...http.CallOption) (rsp *GetGoodReply, err error)
	GetGoodsByKind(ctx context.Context, req *GetGoodsByKindRequest, opts ...http.CallOption) (rsp *GetGoodsReply, err error)
	GetGoodsByName(ctx context.Context, req *GetGoodsByNameRequest, opts ...http.CallOption) (rsp *GetGoodsReply, err error)
	GetGoodsByUserName(ctx context.Context, req *GetGoodsByUserNameRequest, opts ...http.CallOption) (rsp *GetGoodsReply, err error)
	GetOwnGoods(ctx context.Context, req *GetOwnGoodsRequest, opts ...http.CallOption) (rsp *GetGoodsReply, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *GetProfileReply, err error)
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	Register(ctx context.Context, req *RegisterRequest, opts ...http.CallOption) (rsp *RegisterReply, err error)
	UpdateGood(ctx context.Context, req *UpdateGoodRequest, opts ...http.CallOption) (rsp *UpdateGoodReply, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *UpdateProfileReply, err error)
}

type MallHTTPClientImpl struct {
	cc *http.Client
}

func NewMallHTTPClient(client *http.Client) MallHTTPClient {
	return &MallHTTPClientImpl{client}
}

func (c *MallHTTPClientImpl) CreateGood(ctx context.Context, in *CreateGoodRequest, opts ...http.CallOption) (*CreateGoodReply, error) {
	var out CreateGoodReply
	pattern := "/mall/goods"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallCreateGood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...http.CallOption) (*CreateProfileReply, error) {
	var out CreateProfileReply
	pattern := "/user/profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallCreateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) DeleteGoodByID(ctx context.Context, in *DeleteGoodByIDRequest, opts ...http.CallOption) (*DeleteGoodReply, error) {
	var out DeleteGoodReply
	pattern := "/user/good/ID/{ID}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallDeleteGoodByID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) GetGoodByID(ctx context.Context, in *GetGoodByIDRequest, opts ...http.CallOption) (*GetGoodReply, error) {
	var out GetGoodReply
	pattern := "/mall/good/ID/{ID}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetGoodByID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) GetGoodsByKind(ctx context.Context, in *GetGoodsByKindRequest, opts ...http.CallOption) (*GetGoodsReply, error) {
	var out GetGoodsReply
	pattern := "/mall/goods/{Kind}/{Page}/{PageSize}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetGoodsByKind))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) GetGoodsByName(ctx context.Context, in *GetGoodsByNameRequest, opts ...http.CallOption) (*GetGoodsReply, error) {
	var out GetGoodsReply
	pattern := "/user/goods/name/{Name}/{Page}/{PageSize}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetGoodsByName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) GetGoodsByUserName(ctx context.Context, in *GetGoodsByUserNameRequest, opts ...http.CallOption) (*GetGoodsReply, error) {
	var out GetGoodsReply
	pattern := "/user/goods/{UserName}/{Page}/{PageSize}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetGoodsByUserName))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) GetOwnGoods(ctx context.Context, in *GetOwnGoodsRequest, opts ...http.CallOption) (*GetGoodsReply, error) {
	var out GetGoodsReply
	pattern := "/user/goods/{Page}/{PageSize}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetOwnGoods))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*GetProfileReply, error) {
	var out GetProfileReply
	pattern := "/user/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) Register(ctx context.Context, in *RegisterRequest, opts ...http.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	pattern := "/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) UpdateGood(ctx context.Context, in *UpdateGoodRequest, opts ...http.CallOption) (*UpdateGoodReply, error) {
	var out UpdateGoodReply
	pattern := "/mall/goods"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateGood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*UpdateProfileReply, error) {
	var out UpdateProfileReply
	pattern := "/user/profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallUpdateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
